version: 0.1


env:
  parameter-store:
    REPOSITORY_URI: "repo_uri"
    AWS_DEFAULT_REGION: "region"
    AWS_ACCESS_KEY_ID: "key_id"
    AWS_SECRET_ACCESS_KEY: "main_key"
    IMAGE_TAG: "IMAGE_TAG"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo  $AWS_DEFAULT_REGION
      - echo  $AWS_ACCESS_KEY_ID
      - echo  $AWS_SECRET_ACCESS_KEY
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date` $IMAGE_TAG
      - echo Building the Docker image...
      - echo RepoURI $REPOSITORY_URI
      - docker build -t "751898685448.dkr.ecr.us-east-2.amazonaws.com/angular_django:latest" .
  post_build:
    commands:
      - docker images
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest

      - echo Writing image definitions file...
      - mkdir -p out
      - printf '[{"name":"angular_django_container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > out/honeycomb.json
artifacts:
    files: out/*.json
